### ISSUE TITLE
regex in documentation is wrong

### ISSUE THREAD

**Issue by Joel05** [SebiAi/custom-nothing-glyph-tools#1]
The regex given in the documentation is wrong. It accepts values from 0-999, while it should accept 0-100. 
This one should work (at least when playing around in regex101 i found no flaws):
`^([1-5])-(\d{1,2}|100)(?:-(\d{1,2}|100))?(?:-(EXP|LIN))?$`

**Comment by SebiAi** [comment]
Jup, thank you very much.
I did not know how to cap it between 0 and 100.
I will add it right now!
