### ISSUE TITLE
Got an error while setting things up!

### ISSUE THREAD

**Issue by priyanshu-kun** [SebiAi/custom-nothing-glyph-tools#15]
**Describe the bug**
Hey man, Great work you really made my day! but there is a problem with my setup which is when I try to run `python3 custom-nothing-glyph-tools/GlyphTranslator.py Label.txt` command I got `Traceback (most recent call last):
  File "custom-nothing-glyph-tools/GlyphTranslator.py", line 27, in <module>
    GlyphsPhone2: list[list[int]] = [
TypeError: 'type' object is not subscriptable` error in terminal.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.04

**Comment by SebiAi** [comment]
What python version do you have?

**Comment by priyanshu-kun** [comment]
Python 3.8.15

**Comment by SebiAi** [comment]
Can you redownload the archive and tell me if you still encounter this error?
Download: https://github.com/SebiAi/custom-nothing-glyph-tools/archive/refs/heads/main.zip

**Comment by priyanshu-kun** [comment]
No, still it does not working although when I try to install new requirements for the project it says the things are already installed in system.
```
Requirement already satisfied: termcolor in /home/priyanshu/.pyenv/versions/3.8.15/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2.3.0)
Requirement already satisfied: mido in /home/priyanshu/.pyenv/versions/3.8.15/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: colorama>=0.4.6 in /home/priyanshu/.pyenv/versions/3.8.15/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (0.4.6)
Requirement already satisfied: packaging~=23.1 in /home/priyanshu/.pyenv/versions/3.8.15/lib/python3.8/site-packages (from mido->-r requirements.txt (line 2)) (23.2)
```

**Comment by SebiAi** [comment]
> No, still it does not working although when I try to install new requirements for the project it says the things are already installed in system.

Still the same error?

I'll try to reproduce this error - will need to set up a VM.

**Comment by SebiAi** [comment]
Ok, just set up a clean VM with Ubuntu 22.04.3 LTS:
```bash
$ uname --all
Linux vmuser-VirtualBox 6.2.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

After manually installing pip (`sudo apt install python3-pip`) and then the *requirements.txt* it works just fine for me.
I managed to use the *GlyphTranslator* and the *GlyphModder* on the `Examples/Compatibility mode/Ricky/` example.

My python version: Python 3.10.12

Please try this and see if the example also works for you:
```bash
cd custom-nothing-glyph-tools-main
python3 GlyphTranslator.py Examples/Compatibility\ mode/Ricky/Ricky.txt
```

**Comment by priyanshu-kun** [comment]
Bro, still not working!

**Comment by SebiAi** [comment]
I think your python version is to old. Try upgrading it.

Other than that I have no idea. I can't even reproduce it. You can try to remove the explicit variable types and then try again.
