### ISSUE TITLE
[FEATURE] Sample pack

### ISSUE THREAD

**Issue by PabloOyarzo** [SebiAi/custom-nothing-glyph-tools#16]
Have you seen a way of making a sample instead of just a ringtone?

**Comment by SebiAi** [comment]
What do you mean by that? Can you please elaborate further?
Do you mean a sample pack for the Glyph Composer?

 You can create a notification tone if you mean that.

**Comment by PabloOyarzo** [comment]
Yes I mean for the composer!

**Comment by SebiAi** [comment]
> Yes I mean for the composer!

This is not the goal of this project, but you can use it for that if you know how to decompile the Glyph Composer, replace the assets and then recompile the project.

Do something like this, I have not tried it myself:
1. Export your audio as wav (waveform file)
2. Create the labels file as normal
3. Use the GlyphTranslator to translate the labels file
4. Decompile the Glyph Composer apk - you can get it from apkmirror (I used [JADX](https://github.com/skylot/jadx) to decompile it for myself)
5. Replace the audio and csv file in `resources/assets/glyphs` (rename and use the `glypha` as the csv file)
6. Recompile and sign - don't know about that part (Use Google or try to figure out how ReVanced patches the apks)
7. Install custom apk
8. Profit?

Use Google and be smart about it :+1:
