### ISSUE TITLE
[BUG] GlyphModder will not override the metadata tags when the tags already exist

### ISSUE THREAD

**Issue by SebiAi** [SebiAi/custom-nothing-glyph-tools#17]
**Describe the bug**
When writing to an audio file, which was already written to before, the metadata tags get not updated and remain unchanged.

**To Reproduce**
1. Write the `glypha` and `glyphc1` files to a blank audio file
2. Modify the `glypha`/`glyphc1` files
3. Write them again to the same audio file used in step 1
4. The metadata did not change

**Expected behavior**
The metadata gets overwritten.

**Desktop (please complete the following information):**
 - OS: Windows, maybe others

**Additional context**
Output of the GlyphModder on Windows:
```
python GlyphModder.py -t "LetYouDown" -w labels.glypha labels.glyphc1 LetYouDOwn.ogg
INFO: Auto detected Phone (2) mode.
INFO: ffmpeg command is longer than 32764 characters which is the limit on Windows. Saving metadata to file and passing it to ffmpeg.
Wrote 34964 bytes of AUTHOR metadata
Wrote 466 bytes of CUSTOM1 metadata
```
Important is that the external file workaround for the metadata was used.

**Workarround**
You can use this ffmpeg command to strip the audio of ALL its metadata tags:
```bash
ffmpeg -i audio.ogg -map_metadata -1 -c:a copy -fflags +bitexact -flags:v +bitexact -flags:a +bitexact audio_clean.ogg
```
Now pass `audio_clean.ogg` to the *GlyphModder*  script instead of `audio.ogg`.

**Comment by MIP2006** [comment]
"Bypassed" by making a blank ogg file and writing the files on it, pretty weird and never happened to me before.
