### ISSUE TITLE
[FEATURE] Image Phone2

### ISSUE THREAD

**Issue by DOCIS-007** [SebiAi/custom-nothing-glyph-tools#18]
Change the image in the documentation.
![Phone2 ](https://github.com/SebiAi/custom-nothing-glyph-tools/assets/56439612/d1480f3e-901a-4d82-b0fd-0e4bcaf6c7c5)

**Comment by SebiAi** [comment]
This looks phenomenal.

I think having the Zones and the normal Phone (2) Glyphs in one picture is a bit confusing.

Could you separate the two?

**Comment by DOCIS-007** [comment]
Not a problem.

![Phone2_2 ](https://github.com/SebiAi/custom-nothing-glyph-tools/assets/56439612/4f0f5885-9f90-47de-8bd6-6bff0a5c8a6d)
![Phone2_1 ](https://github.com/SebiAi/custom-nothing-glyph-tools/assets/56439612/12b97bd6-14a7-4d99-9a2d-576b37373c8b)
](url)

**Comment by SebiAi** [comment]
Thank you for your work, I'll see when I can get it implemented
