### ISSUE TITLE
[BUG] ffmpeg error

### ISSUE THREAD

**Issue by taiixu** [SebiAi/custom-nothing-glyph-tools#20]
When I use GlyphModder, the audio file size becomes 0 bytes. I used ffmpeg directly and this is the error I got: 

![image](https://github.com/SebiAi/custom-nothing-glyph-tools/assets/156664940/775836e2-efef-4294-a442-eac252586005)
![image2](https://github.com/SebiAi/custom-nothing-glyph-tools/assets/156664940/78160a41-5364-4c23-8e36-48c08f31b085)

**Comment by SebiAi** [comment]
First thing I noticed: You have the wrong codec. You have vorbis but you need opus - see [here](https://github.com/SebiAi/custom-nothing-glyph-tools#wrong-codec).

Try fixing that and then check if the error still happens.

If it does, provide me with the following info:
* What version of ffmpeg do you have? (`ffmpeg -version`)
* Did you use the latest version of the custom-nothing-glyph-tools (redownload the zip)?

Can you also attach the glypha file and glyphc1 file?

**Comment by taiixu** [comment]
Re-encoding didn't solve my problem 
https://cdn.discordapp.com/attachments/544797896042741769/1205918478104797294/2024-02-10_19-42-55.mp4?ex=65da1e1a&is=65c7a91a&hm=ec4bc7fe4d9d48d511edaba39516f1289451b8383e68b23dbb88def34b54e148&

```
ffmpeg version N-55702-g920046a
built on Aug 21 2013 18:10:00 with gcc 4.7.3 (GCC)
configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
libavutil      52. 42.100 / 52. 42.100
libavcodec     55. 29.100 / 55. 29.100
libavformat    55. 14.101 / 55. 14.101
libavdevice    55.  3.100 / 55.  3.100
libavfilter     3. 82.100 /  3. 82.100
libswscale      2.  5.100 /  2.  5.100
libswresample   0. 17.103 /  0. 17.103
libpostproc    52.  3.100 / 52.  3.100
```

python version: 3.12.1

**Comment by taiixu** [comment]
glypha: https://cdn.discordapp.com/attachments/544797896042741769/1205920114365562952/label.glypha?ex=65da1fa0&is=65c7aaa0&hm=491c7e8eb139907a6f8d64ef85d6e20030df45479e426d7c68b0bd9e5391a2ad&

**Comment by SebiAi** [comment]
Seems like your ffmpeg version is quite old (2013). Please follow these steps and see if that fixes it:
1. Download the latest ffmpeg build from [here](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip)
2. Extract the zip
3. Use the `--ffmpeg` parameter in the *GlyphModder* to pass in the full path to the ffmpeg binary you just extracted (drag in the executable into the terminal window to auto complete the path)

**Comment by taiixu** [comment]
Oh, thanks, that solved the problem.
