### ISSUE TITLE
[BUG] Importing Giving Issues

### ISSUE THREAD

**Issue by abirxgpt** [SebiAi/custom-nothing-glyph-tools#21]
**Describe the bug**
Import Failed. File is not Produced by the Composer
**To Reproduce**
I made that following the same you taught on youtube but still getting issues

![Screenshot_20240215-011548](https://github.com/SebiAi/custom-nothing-glyph-tools/assets/142162873/47044e21-7d98-4020-8c2a-40e2bab1e6ae)

**Expected behavior**
It must be Imported 

**Screenshots**
My Metadata Images:
![image](https://github.com/SebiAi/custom-nothing-glyph-tools/assets/142162873/bc499a18-3dc2-4dfb-a6d0-2f774b39bea8)

![image](https://github.com/SebiAi/custom-nothing-glyph-tools/assets/142162873/9ca8fe0b-3ef1-4d87-9d19-77219db39ee0)
 - OS: [e.g. Used Windows]

**Comment by Snupai** [comment]
From the ffprobe it looks like the codec you have chosen to export the cut audio was vorbis and not opus.
Try exporting it as opus.
https://github.com/SebiAi/custom-nothing-glyph-tools?tab=readme-ov-file#wrong-codec

**Comment by SebiAi** [comment]
This is not a bug, you just exported the audio in the wrong encoding (vorbis instead of opus).

See Snupai's message or the troubleshooting chapter for more information.
