### ISSUE TITLE
[FEATURE] Support for 2a

### ISSUE THREAD

**Issue by AlEmerich** [SebiAi/custom-nothing-glyph-tools#26]
Hello ! 

I just received my 2a and woud love to use your soft :) 

I will try do it myself, tho

**Comment by SebiAi** [comment]
I am working on a rewrite of the scripts and there may be something planed for the 2a. See here: https://github.com/SebiAi/custom-nothing-glyph-tools/blob/main/docs/news/2024-03-10_custom-nothing-glyph-tools%20rewrite.md

**Comment by AlEmerich** [comment]
Nice ! Thanks a lot for your work :pray:
