### ISSUE TITLE
[FEATURE] Adapt the README to a wiki

### ISSUE THREAD

**Issue by SebiAi** [SebiAi/custom-nothing-glyph-tools#4]
The README is getting quite confusing and convoluted.
It would be better if we have a wiki with multiple pages which can referenced from other wiki pages or the README.

**Comment by alexhmdev** [comment]
Hi! I loved you app! could I help you with that wiki using astro? that way we can attach it to Github pages, probably a nice feature to this awesome App!

**Comment by SebiAi** [comment]
> Hi! I loved you app! could I help you with that wiki using astro? that way we can attach it to Github pages, probably a nice feature to this awesome App!

Never used Astro. What are the benefits of creating the documentation with Astro? How steep is the learning curve for someone who has never touched web development?
