### ISSUE TITLE
[OBSERVATION] System Ringtones & Composer -> System Glyph Player discrepancy

### ISSUE THREAD

**Issue by nidzulaa** [SebiAi/custom-nothing-glyph-tools#8]
An option to export system-like ringtone / notification .ogg
I've noticed that the system .ogg's have different types of encoding, for example ffprobe stats for 02_swanny.ogg
```
Input #0, ogg, from '.\02_swanny.ogg':
  Duration: 00:00:00.45, start: 0.000000, bitrate: 468 kb/s
  Stream #0:0: Audio: vorbis, 48000 Hz, stereo, fltp, 499 kb/s
    Metadata:
      ENCODED-BY      : Switch Plus © NCH Software
      TITLE           : swanny
      COMMENT         : Composed by Mattias Tengér & Tom Ridley
                      : Mastered by Tom Ridley
      PRODUCER        : Tom Ridley
      COPYRIGHT       : 2022 Nothing Technology Limited
      ENCODEDBY       : Switch Plus © NCH Software
      ENCODER         : libaudio: vorbisenc;Switch Plus © NCH Software
```

Also their composer is playing the custom songs without any issues, while the system player makes the lights flicker or makes it look less responsive

**Comment by SebiAi** [comment]
The data for the songs is somewhere in the OS - I don't think that it is saved in the audio file.

If you want to do your own glyph lighting with this Nothing Rintone just convert it to the right format with ffmpeg - then you can use my tools just fine.

The composer and system os (ringtone settings) discrepancy is already known - Nothing is working on a fix.
